apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hyperroute

resources:
  - namespace.yaml
  - agent-fsm-colocated-pod.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: hyperroute-mesh
