server:
  port: 8080

spring:
  application:
    name: hyperroute-gateway
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  cloud:
    gateway:
      routes:
        # Route 1: Orders (Standard L7 Reverse Proxy)
        - id: orders-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@apiKeyResolver}"

        # Route 2: Faulty Payments (Circuit Breaker & Fallback Test)
        - id: payments-fault-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentsCircuitBreaker
                fallbackUri: forward:/fallback/payments
                statusCodes:
                  - 500
                  - 503

resilience4j:
  circuitbreaker:
    instances:
      paymentsCircuitBreaker:
        slidingWindowSize: 6
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
