# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fsm_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fsm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66sm_service.proto\x12\x0b\x61pexgateway\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n\x11TransitionRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x10\n\x08\x61lert_id\x18\x02 \x01(\t\x12/\n\x0fproposed_action\x18\x03 \x01(\x0e\x32\x16.hyperroute.FSMAction\x12\x10\n\x08\x66indings\x18\x04 \x01(\t\"\xb3\x01\n\x12TransitionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0fresulting_state\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x10\n\x08trace_id\x18\x04 \x01(\t\x12\x1a\n\x12\x61udit_dossier_hash\x18\x05 \x01(\t\x12\x34\n\x10\x63ommit_timestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\xc1\x01\n\tFSMAction\x12\x16\n\x12\x46SM_ACTION_UNKNOWN\x10\x00\x12\x15\n\x11\x43LEAR_TRANSACTION\x10\x01\x12\x18\n\x14\x43LEAR_WITH_EXCEPTION\x10\x02\x12\x15\n\x11\x45SCALATE_TO_HUMAN\x10\x03\x12\x1d\n\x19\x46REEZE_FUNDS_AND_ESCALATE\x10\x04\x12\x1d\n\x19TRIGGER_AUDIT_INVESTIGATE\x10\x05\x12\x16\n\x12REJECT_TRANSACTION\x10\x06\x32`\n\nFSMService\x12R\n\x0fTransitionState\x12\x1e.hyperroute.TransitionRequest\x1a\x1f.hyperroute.TransitionResponseB0Z.github.com/swikarpat/hyperroute-contracts/fsmb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fsm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/swikarpat/hyperroute-contracts/fsm'
  _globals['_FSMACTION']._serialized_start=374
  _globals['_FSMACTION']._serialized_end=567
  _globals['_TRANSITIONREQUEST']._serialized_start=67
  _globals['_TRANSITIONREQUEST']._serialized_end=189
  _globals['_TRANSITIONRESPONSE']._serialized_start=192
  _globals['_TRANSITIONRESPONSE']._serialized_end=371
  _globals['_FSMSERVICE']._serialized_start=569
  _globals['_FSMSERVICE']._serialized_end=665
# @@protoc_insertion_point(module_scope)
