# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fsm_service_pb2 as fsm__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fsm_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FSMServiceStub(object):
    """Deterministic State Machine Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransitionState = channel.unary_unary(
                '/hyperroute.FSMService/TransitionState',
                request_serializer=fsm__service__pb2.TransitionRequest.SerializeToString,
                response_deserializer=fsm__service__pb2.TransitionResponse.FromString,
                _registered_method=True)


class FSMServiceServicer(object):
    """Deterministic State Machine Service
    """

    def TransitionState(self, request, context):
        """Hot path: validates agent proposed actions against regulatory transition matrix
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FSMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransitionState': grpc.unary_unary_rpc_method_handler(
                    servicer.TransitionState,
                    request_deserializer=fsm__service__pb2.TransitionRequest.FromString,
                    response_serializer=fsm__service__pb2.TransitionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hyperroute.FSMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hyperroute.FSMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FSMService(object):
    """Deterministic State Machine Service
    """

    @staticmethod
    def TransitionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperroute.FSMService/TransitionState',
            fsm__service__pb2.TransitionRequest.SerializeToString,
            fsm__service__pb2.TransitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
